
name: crypto

on:
  workflow_dispatch: {}
  push:
    branches: [ 'main' ]
    paths:    [ 'crypto/*' ]

jobs:
  crypto:

    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: windows, cc: msvc,  arch: x64,    runs: windows-2025          }
          - { os: windows, cc: clang, arch: x64,    runs: windows-2025          }
          - { os: windows, cc: msvc,  arch: arm64,  runs: windows-11-vs2026-arm }
          - { os: windows, cc: clang, arch: arm64,  runs: windows-11-vs2026-arm }
          - { os: linux,   cc: clang, arch: x64,    runs: ubuntu-26.04          }
          - { os: linux,   cc: gcc,   arch: x64,    runs: ubuntu-26.04          }
          - { os: linux,   cc: clang, arch: arm64,  runs: ubuntu-26.04-arm      }
          - { os: linux,   cc: gcc,   arch: arm64,  runs: ubuntu-26.04-arm      }
          - { os: macos,   cc: clang, arch: x64,    runs: macos-26-intel        }
          - { os: macos,   cc: clang, arch: arm64,  runs: macos-26              }
          - { os: mingw,   cc: clang, arch: x64,    runs: ubuntu-26.04          }
#          - { os: mingw,   cc: gcc,   arch: x64,    runs: ubuntu-26.04          }
          - { os: wasi,    cc: clang, arch: wasm32, runs: ubuntu-26.04          }

    name: ${{ matrix.os }}-${{ matrix.cc }}-${{ matrix.arch }}

    runs-on: ${{ matrix.runs }}

    steps:

      - uses: actions/checkout@v6

      - uses: ./.github/workflows/shared
        with:
          os: ${{ matrix.os }}
          cc: ${{ matrix.cc }}
          arch: ${{ matrix.arch }}

      - id: crypto-test-cache
        uses: actions/cache@v5
        with:
          path: crypto/utils/generated/*.h
          key: crypto-test-cache
          enableCrossOsArchive: true

      - name: generate tests
        if: steps.crypto-test-cache.outputs.cache-hit != 'true'
        run: python crypto/utils/test_generate.py

      - name: windows tests
        if: ${{ matrix.os == 'windows' }}
        shell: cmd
        run: |
          if "${{ matrix.arch }}" equ "x64" set SDE=-arl
          set PATH=%CD%\sde;%PATH%
          call scripts\xrun.cmd crypto\utils\test.c  "${{ matrix.os }}" "${{ matrix.cc }}" "${{ matrix.arch }}" norun c++ || exit /b
          call scripts\xrun.cmd crypto\utils\test.c  "${{ matrix.os }}" "${{ matrix.cc }}" "${{ matrix.arch }}"           || exit /b

      - name: non-windows tests
        if: ${{ matrix.os != 'windows' }}
        shell: bash
        run: |
          export PATH=$(pwd)/sde:${PATH}
          [[ "${{ matrix.os }}" == "linux" && "${{ matrix.arch }}" == "x64" ]] && export SDE=-arl
          scripts/xrun.sh crypto/utils/test.c  "${{ matrix.os }}" "${{ matrix.cc }}" "${{ matrix.arch }}" norun c++
          scripts/xrun.sh crypto/utils/test.c  "${{ matrix.os }}" "${{ matrix.cc }}" "${{ matrix.arch }}"
