
name: float_rounding

on:
  workflow_dispatch: {}
  push:
    branches: [ 'main' ]
    paths:    [ 'float_rounding/*' ]

jobs:
  float-rounding:

    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: windows, cc: msvc,  arch: x64,    runs: windows-2025          }
          - { os: windows, cc: clang, arch: x64,    runs: windows-2025          }
          - { os: windows, cc: msvc,  arch: arm64,  runs: windows-11-vs2026-arm }
          - { os: windows, cc: clang, arch: arm64,  runs: windows-11-vs2026-arm }
          - { os: linux,   cc: clang, arch: x64,    runs: ubuntu-26.04          }
          - { os: linux,   cc: gcc,   arch: x64,    runs: ubuntu-26.04          }
          - { os: linux,   cc: clang, arch: arm64,  runs: ubuntu-26.04-arm      }
          - { os: linux,   cc: gcc,   arch: arm64,  runs: ubuntu-26.04-arm      }
          - { os: linux,   cc: clang, arch: rv64,   runs: ubuntu-26.04          }
          - { os: linux,   cc: gcc,   arch: rv64,   runs: ubuntu-26.04          }
          - { os: macos,   cc: clang, arch: x64,    runs: macos-26-intel        }
          - { os: macos,   cc: clang, arch: arm64,  runs: macos-26              }
          - { os: mingw,   cc: clang, arch: x64,    runs: ubuntu-26.04          }
          - { os: mingw,   cc: gcc,   arch: x64,    runs: ubuntu-26.04          }
          - { os: wasi,    cc: clang, arch: wasm32, runs: ubuntu-26.04          }

    name: ${{ matrix.os }}-${{ matrix.cc }}-${{ matrix.arch }}

    runs-on: ${{ matrix.runs }}

    steps:

      - uses: actions/checkout@v6

      - uses: ./.github/workflows/shared
        with:
          os: ${{ matrix.os }}
          cc: ${{ matrix.cc }}
          arch: ${{ matrix.arch }}

      - if: ${{ matrix.os == 'windows' }}
        shell: cmd
        run: |
          call scripts\xrun.cmd float_rounding\float_rounding_test.c "${{ matrix.os }}" "${{ matrix.cc }}" "${{ matrix.arch }}" -DQUICK_TEST c++ norun
          call scripts\xrun.cmd float_rounding\float_rounding_test.c "${{ matrix.os }}" "${{ matrix.cc }}" "${{ matrix.arch }}" -DQUICK_TEST c

      - if: ${{ matrix.os == 'windows' && matrix.arch == 'x64' }}
        shell: cmd
        run: |
          call scripts\xrun.cmd float_rounding\float_rounding_test.c "${{ matrix.os }}" "${{ matrix.cc }}" "${{ matrix.arch }}" -DQUICK_TEST c sse4

      - if: ${{ matrix.os != 'windows' }}
        shell: bash
        run: |
          scripts/xrun.sh float_rounding/float_rounding_test.c "${{ matrix.os }}" "${{ matrix.cc }}" "${{ matrix.arch }}" -DQUICK_TEST c++ norun
          scripts/xrun.sh float_rounding/float_rounding_test.c "${{ matrix.os }}" "${{ matrix.cc }}" "${{ matrix.arch }}" -DQUICK_TEST c

      - if: ${{ matrix.os != 'windows' && matrix.arch == 'x64' }}
        shell: bash
        run: |
          scripts/xrun.sh float_rounding/float_rounding_test.c "${{ matrix.os }}" "${{ matrix.cc }}" "${{ matrix.arch }}" -DQUICK_TEST c sse4
